<a href="https://colab.research.google.com/github/waqasahmad-developer/PCA-Digit-Recognizer-MNIST-/blob/main/MINST_PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Without using PCA**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import time
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('train.csv')

In [ ]:
df.sample(5)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
18380      6       0       0       0       0       0       0       0       0   
2323       1       0       0       0       0       0       0       0       0   
26205      0       0       0       0       0       0       0       0       0   
21082      8       0       0       0       0       0       0       0       0   
8328       8       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
18380       0  ...         0         0         0         0         0   
2323        0  ...         0         0         0         0         0   
26205       0  ...         0         0         0         0         0   
21082       0  ...         0         0         0         0         0   
8328        0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
18380         0         0         0         0         0  
2323          0         0         0         0         0  
26205         0         0         0         0         0  
21082         0         0         0         0         0  
8328          0         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
df.shape

(42000, 785)

In [ ]:
X = df.iloc[:,1:]
Y = df.iloc[:,0]

In [ ]:
Y.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [ ]:
#spiliting the data in train, test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
#fiting the model with the 784 cols
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
#finding the time duration which it takes for 784 cols
start = time.time()
y_pred = knn.predict(X_test)
print(time.time() - start)

16.21312642097473


In [ ]:
#finding the accuracy score
accuracy_score(y_test,y_pred)

0.9648809523809524

**Applying PCA**

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
#scaling the data for PCA
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
#importing PCA from sklearn
from sklearn.decomposition import PCA

#creating an instance of PCA
pca = PCA(n_components=200)  # n_components as a parameter in which we pass the components numbers which we want to select

In [ ]:
#transforming the X_train and X_test
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [ ]:
X_train_trf.shape

(33600, 200)

In [ ]:
knn = KNeighborsClassifier()

In [ ]:
#fiting the model to transformed data
knn.fit(X_train_trf,y_train)

KNeighborsClassifier()

In [ ]:
#finding the time duration for 200 cols
start = time.time()
y_pred = knn.predict(X_test_trf)
print(time.time() - start)

3.65061616897583


In [ ]:
#finding accuracy score after PCA
accuracy_score(y_test,y_pred)

0.9507142857142857

In [ ]:
# A loop which will runs 784 times and will find accuracy score after every iteration from this we can find out that how many features are important to acheive good accuracy score
for i in range(1,785):
    pca = PCA(n_components=i)
    X_train_trf = pca.fit_transform(X_train)
    X_test_trf = pca.transform(X_test)

    knn = KNeighborsClassifier()

    knn.fit(X_train_trf,y_train)

    y_pred = knn.predict(X_test_trf)

    print(accuracy_score(y_test,y_pred))


0.2580952380952381
0.3236904761904762
0.5104761904761905
0.6663095238095238
0.7378571428571429
0.8227380952380953
0.8436904761904762
0.8721428571428571
0.886547619047619
0.9055952380952381
0.9116666666666666
0.9184523809523809
0.9276190476190476
0.9351190476190476
0.9384523809523809
0.9379761904761905
0.9407142857142857
0.94
0.9425
0.9442857142857143
0.9438095238095238
0.9441666666666667
0.9442857142857143
0.9457142857142857
0.9484523809523809
0.9479761904761905
0.9478571428571428
0.9471428571428572
0.949047619047619
0.9491666666666667
0.9507142857142857
0.9513095238095238
0.95
0.9504761904761905
0.950952380952381
0.9519047619047619
0.9517857142857142
0.9527380952380953
0.9533333333333334
0.9528571428571428
0.9522619047619048
0.9522619047619048
0.9523809523809523
0.9533333333333334
0.9528571428571428
0.9530952380952381
0.9530952380952381
0.9533333333333334
0.9527380952380953
0.9533333333333334
0.9545238095238096
0.954047619047619
0.9541666666666667
0.9541666666666667
0.9546428571428571

**Visualizing the data in 2D shape**

In [ ]:
pca = PCA(n_components=2)
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [ ]:
X_train_trf.shape

(33600, 2)

In [ ]:
import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter(x=X_train_trf[:,0],
                 y=X_train_trf[:,1],
                 color=y_train_trf,
                 color_discrete_sequence=px.colors.qualitative.G10
                )
fig.show()

****

**Visualizing the data in 3D shape**


In [ ]:
pca = PCA(n_components = 3)
X_train_trf = pca.fit_transform(X_train)
X_test_trf = pca.transform(X_test)

In [ ]:
import plotly.express as px
y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=X_train_trf[:,0], y=X_train_trf[:,1], z=X_train_trf[:,2],
              color=y_train_trf)
fig.update_layout(
    margin=dict(l=20, r=20, t=20, b=20),
    paper_bgcolor="LightSteelBlue",
)
fig.show()

In [ ]:
#Eigen values
pca.explained_variance_

array([40.67111198, 29.17023401, 26.74459621])

In [ ]:
#Eigen vectors
pca.components_.shape

(3, 784)

In [ ]:
#finding the percentage for each component
pca.explained_variance_ratio_

array([0.05785192, 0.0414927 , 0.03804239])

In [ ]:
#finding the variance
np.cumsum(pca.explained_variance_ratio_)

array([0.05785192, 0.09934462, 0.13738701])

In [1]:
#from this graph we can see that how many components we actually need to acheive 90% variance
plt.plot(np.cumsum(pca.explained_variance_ratio_))

NameError: name 'plt' is not defined